MarketPlace-O2O-Platform/MarketPlace-Server

src/main/java/com/appcenter/marketplace/domain/coupon/controller/CouponController.java, src/main/java/com/appcenter/marketplace/domain/coupon/domain/Coupon.java, src/main/java/com/appcenter/marketplace/domain/coupon/dto/req/CouponReqDto.java, src/main/java/com/appcenter/marketplace/domain/coupon/dto/res/CouponInfoResDto.java, src/main/java/com/appcenter/marketplace/domain/coupon/repository/CouponRepository.java, src/main/java/com/appcenter/marketplace/domain/coupon/service/CouponService.java, src/main/java/com/appcenter/marketplace/domain/coupon/service/impl/CouponServiceImpl.java, src/main/java/com/appcenter/marketplace/domain/member_coupon/MemberCoupon.java
close #3 
**체크해주세요!**
- service 에서 marketId로 존재 유무 판단하는 코드는 아직 작성하지 않았습니다.
- service interface 로 생성해, 클래스로 상속받는 구조로 생성하였습니다.
=> [Feat] 쿠폰 등록 API 구현

src/main/java/com/appcenter/marketplace/domain/category/Category.java, src/main/java/com/appcenter/marketplace/domain/category/CategoryRepository.java, src/main/java/com/appcenter/marketplace/domain/market/Market.java, src/main/java/com/appcenter/marketplace/domain/market/MarketRepository.java, src/main/java/com/appcenter/marketplace/domain/market/controller/MarketOwnerController.java, src/main/java/com/appcenter/marketplace/domain/market/dto/req/MarketCreateReqDto.java, src/main/java/com/appcenter/marketplace/domain/market/dto/req/MarketUpdateReqDto.java, src/main/java/com/appcenter/marketplace/domain/market/dto/res/MarketResDto.java, src/main/java/com/appcenter/marketplace/domain/market/service/MarketOwnerService.java, src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketOwnerServiceImpl.java, src/main/java/com/appcenter/marketplace/global/common/Major.java
close #5 
<br>
- Enum 타입 Major에 String 값으로 필드값이 존재하는지 확인하는 메소드 추가
- Category 테이블과 Market 테이블 일대일 관계에서 다대일 관계로 변경
- Category Repository 생성
<br>
-  이미지는 나중에 넣는걸 작성하는걸로 가정함
-  카테고리 테이블 데이터가 있다고 가정하고 요청에서 대분류 필드를 받아와서 조회함(배포하게되면 db에 직접 데이터를 넣어야할 듯)
<br>
=> [Feat/#5] 마켓 CRUD API 구현

src/main/java/com/appcenter/marketplace/domain/market/Market.java, src/main/java/com/appcenter/marketplace/domain/market/controller/MarketOwnerController.java, src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketOwnerServiceImpl.java, src/main/java/com/appcenter/marketplace/global/common/StatusCode.java
<br>
close #11 
<br>
<br>
<br>
-
<br>
<br>
=> [Refactor/#11] 마켓 유효성 검사 및 예외처리

build.gradle, src/main/java/com/appcenter/marketplace/domain/coupon/controller/CouponController.java, src/main/java/com/appcenter/marketplace/domain/coupon/service/impl/CouponServiceImpl.java, src/main/java/com/appcenter/marketplace/global/common/StatusCode.java
<br>
close #12 
<br>
<br>
<br>
-
<br>
<br>
=> [Refactor/#12] 쿠폰 유효성 검사 및 예외처리 로직  수정

build.gradle, src/main/java/com/appcenter/marketplace/global/config/MysqlConfig.java, src/main/java/com/appcenter/marketplace/global/config/OracleConfig.java, src/main/java/com/appcenter/marketplace/global/oracleRepository/InuLoginRepository.java, src/main/resources/application.properties
<br>
close #14 
<br>
<br>
<br>
-
<br>
<br>
=> [Env/#14] 다중 DB 연결을 위한 Config 설정 및 교내 학생 인증 쿼리 추가

.github/workflows/cicd.yml
<br>
close #18 
<br>
<br>
<br>
-
<br>
<br>
=> [Feat/#18] ci/cd.yml 배포

src/main/java/com/appcenter/marketplace/MarketplaceApplication.java, src/main/java/com/appcenter/marketplace/domain/category/Category.java, src/main/java/com/appcenter/marketplace/domain/coupon/Coupon.java, src/main/java/com/appcenter/marketplace/domain/coupon/controller/CouponController.java, src/main/java/com/appcenter/marketplace/domain/coupon/dto/req/CouponReqDto.java, src/main/java/com/appcenter/marketplace/domain/favorite/Favorite.java, src/main/java/com/appcenter/marketplace/domain/image/Image.java, src/main/java/com/appcenter/marketplace/domain/market/Market.java, src/main/java/com/appcenter/marketplace/domain/member/Member.java, src/main/java/com/appcenter/marketplace/domain/member/MemberRepository.java, src/main/java/com/appcenter/marketplace/domain/member/controller/MemberController.java, src/main/java/com/appcenter/marketplace/domain/member/dto/req/MemberLoginReqDto.java, src/main/java/com/appcenter/marketplace/domain/member/dto/res/MemberLoginResDto.java, src/main/java/com/appcenter/marketplace/domain/member/service/MemberService.java, src/main/java/com/appcenter/marketplace/domain/member/service/impl/MemberServiceImpl.java, src/main/java/com/appcenter/marketplace/domain/member_coupon/MemberCoupon.java, src/main/java/com/appcenter/marketplace/global/common/Major.java, src/main/java/com/appcenter/marketplace/global/common/StatusCode.java, src/main/java/com/appcenter/marketplace/global/config/OracleConfig.java, src/main/java/com/appcenter/marketplace/global/oracleRepository/InuLoginRepository.java, src/main/resources/application-dev.properties, src/main/resources/application-prod.properties, src/main/resources/application.properties
<br>
close #23 
<br>
- 카테고리 설정
- 마켓, 쿠폰 테스트 insert
<br><br>
- application.properties 파일 "dev" 설정 확인 
> The following 1 profile is active: "dev"
<br><br>
- application.properties 파일 구분 (application-dev, application-prod)
- MySQL DB 설정 -> 테이블 명, 컬럼 명 고정 설정 
<br>
<br>
=> [Feat/#23] INU 학번 로그인 기능 구현 + MySQL 테이블명 고정 설정 + 프로퍼티 파일 구분

src/main/java/com/appcenter/marketplace/domain/member/service/impl/MemberServiceImpl.java, src/main/java/com/appcenter/marketplace/global/config/OracleConfig.java, src/main/java/com/appcenter/marketplace/global/config/SwaggerConfig.java, src/main/resources/application-dev.properties, src/main/resources/application-prod.properties
<br>
close #25 
<br>
<br>
<br>
-
<br>
<br>
=> [Refactor/#25] Swagger 서버 URL 프로퍼티 파일 분리 

build.gradle, src/main/generated/com/appcenter/marketplace/domain/category/QCategory.java, src/main/generated/com/appcenter/marketplace/domain/coupon/QCoupon.java, src/main/generated/com/appcenter/marketplace/domain/favorite/QFavorite.java, src/main/generated/com/appcenter/marketplace/domain/image/QImage.java, src/main/generated/com/appcenter/marketplace/domain/market/QMarket.java, src/main/generated/com/appcenter/marketplace/domain/member/QMember.java, src/main/generated/com/appcenter/marketplace/domain/member_coupon/QMemberCoupon.java, src/main/generated/com/appcenter/marketplace/global/common/QBaseEntity.java, src/main/java/com/appcenter/marketplace/global/config/QuerydslConfig.java
<br>
close #31 
<br>
<br>
<br>
-
<br>
<br>
=> [Feat/#31] QueryDSL 기본 설정

src/main/generated/com/appcenter/marketplace/domain/image/QImage.java, src/main/generated/com/appcenter/marketplace/domain/image/dto/res/QImageResDto.java, src/main/generated/com/appcenter/marketplace/domain/market/dto/res/QMarketResDto.java, src/main/java/com/appcenter/marketplace/domain/coupon/service/impl/CouponServiceImpl.java, src/main/java/com/appcenter/marketplace/domain/image/Image.java, src/main/java/com/appcenter/marketplace/domain/image/ImageRepository.java, src/main/java/com/appcenter/marketplace/domain/image/dto/res/ImageResDto.java, src/main/java/com/appcenter/marketplace/domain/image/service/ImageService.java, src/main/java/com/appcenter/marketplace/domain/image/service/impl/ImageServiceImpl.java, src/main/java/com/appcenter/marketplace/domain/market/MarketRepository.java, src/main/java/com/appcenter/marketplace/domain/market/controller/MarketOwnerController.java, src/main/java/com/appcenter/marketplace/domain/market/dto/req/MarketImageUpdateReqDto.java, src/main/java/com/appcenter/marketplace/domain/market/dto/res/MarketResDto.java, src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepository.java, src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustom.java, src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustomImpl.java, src/main/java/com/appcenter/marketplace/domain/market/service/MarketOwnerService.java, src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketOwnerServiceImpl.java, src/main/java/com/appcenter/marketplace/global/common/StatusCode.java, src/main/java/com/appcenter/marketplace/global/exception/ExceptionControllerAdvice.java
<br>
Closes #32
<br>
<br>
<br>
-
<br>
<br>
=> [Feat/#32] 매장 이미지 수정 기능 추가, 매장 응답 DTO 및 조회 로직 변경, 매장 삭제 시 이미지 삭제 로직 추가

src/main/java/com/appcenter/marketplace/domain/market/controller/MarketController.java, src/main/java/com/appcenter/marketplace/domain/market/controller/MarketOwnerController.java, src/main/java/com/appcenter/marketplace/domain/market/service/MarketOwnerService.java, src/main/java/com/appcenter/marketplace/domain/market/service/MarketService.java, src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketOwnerServiceImpl.java, src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketServiceImpl.java
<br>
close #35 
<br>
<br>
<br>
-
<br>
<br>
=> [Feat/#35] 매장 정보 조회 통합 api MarketOwnerController,Service-> MarketController,Service 옮김

src/main/java/com/appcenter/marketplace/domain/favorite/Favorite.java, src/main/java/com/appcenter/marketplace/domain/favorite/FavoriteRepository.java, src/main/java/com/appcenter/marketplace/domain/favorite/controller/FavoriteController.java, src/main/java/com/appcenter/marketplace/domain/favorite/service/FavoriteService.java, src/main/java/com/appcenter/marketplace/domain/favorite/service/impl/FavoriteServiceImpl.java, src/main/java/com/appcenter/marketplace/domain/market/dto/res/MarketResDto.java, src/main/java/com/appcenter/marketplace/global/common/StatusCode.java
<br>
close #41 
<br>
<br>
<br>
-
<br>
<br>
=> [Feat/#41] 매장 찜하기 API 구현

src/main/java/com/appcenter/marketplace/domain/favorite/controller/FavoriteController.java, src/main/java/com/appcenter/marketplace/domain/favorite/repository/FavoriteRepository.java, src/main/java/com/appcenter/marketplace/domain/favorite/repository/FavoriteRepositoryCustom.java, src/main/java/com/appcenter/marketplace/domain/favorite/repository/FavoriteRepositoryCustomImpl.java, src/main/java/com/appcenter/marketplace/domain/favorite/service/FavoriteService.java, src/main/java/com/appcenter/marketplace/domain/favorite/service/impl/FavoriteServiceImpl.java
<br>
close #46 
close #48 
<br>
<br>
<br>
-
<br>
<br>
=> [Feat/#46,#48] 찜한 매장 리스트 조회 API 구현, 가장 많은 찜 순 매장 리스트 조회 API 구현

src/main/java/com/appcenter/marketplace/domain/coupon/service/impl/CouponOwnerServiceImpl.java, src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepository.java, src/main/java/com/appcenter/marketplace/domain/member/controller/MemberController.java, src/main/java/com/appcenter/marketplace/domain/member/service/MemberService.java, src/main/java/com/appcenter/marketplace/domain/member/service/impl/MemberServiceImpl.java, src/main/java/com/appcenter/marketplace/domain/member_coupon/service/impl/MemberCouponServiceImpl.java, src/main/java/com/appcenter/marketplace/global/common/StatusCode.java
<br>
close #49 
<br>
<br>
<br>
-
<br>
<br>
=> [Feat/#49] 회원 학번 조회 API 구현

src/main/java/com/appcenter/marketplace/domain/local/Local.java, src/main/java/com/appcenter/marketplace/domain/metro/Metro.java
<br>
close #56 
<br>
<br>
<br>
-
<br>
<br>
=> [Feat] 광역시/도 & 시/구 테이블 생성 - #56

src/main/generated/com/appcenter/marketplace/domain/local/QLocal.java, src/main/generated/com/appcenter/marketplace/domain/market/QMarket.java, src/main/generated/com/appcenter/marketplace/domain/market/dto/res/QMarketResDto.java, src/main/generated/com/appcenter/marketplace/domain/metro/QMetro.java, src/main/java/com/appcenter/marketplace/domain/image/Image.java, src/main/java/com/appcenter/marketplace/domain/image/service/impl/ImageServiceImpl.java, src/main/java/com/appcenter/marketplace/domain/local/repository/LocalRepository.java, src/main/java/com/appcenter/marketplace/domain/local/repository/LocalRepositoryCustom.java, src/main/java/com/appcenter/marketplace/domain/local/repository/LocalRepositoryCustomImpl.java, src/main/java/com/appcenter/marketplace/domain/market/dto/req/MarketCreateReqDto.java, src/main/java/com/appcenter/marketplace/domain/market/dto/res/MarketResDto.java, src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustomImpl.java, src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketOwnerServiceImpl.java, src/main/java/com/appcenter/marketplace/global/common/StatusCode.java
<br>
close #59 
<br>
<br>
<br>
- Image 테이블 squence 컬럼 Uniqe 제약조건 삭제
- Image 순서 변경 로직 수정
<br>
<br>
=> [Feat/#59] 주소 세분화에 따른 Market CRUD 로직 변경

src/main/java/com/appcenter/marketplace/domain/market/controller/MarketController.java, src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustom.java, src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustomImpl.java, src/main/java/com/appcenter/marketplace/domain/market/service/MarketService.java, src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketServiceImpl.java
<br>
close #75 
<br>
<br>
<br>
-
<br>
<br>
=> [Feat/#75] 주소 별 매장 리스트 조회 API 구현

src/main/generated/com/appcenter/marketplace/domain/market/dto/res/QFavoriteMarketRes.java, src/main/generated/com/appcenter/marketplace/domain/market/dto/res/QMarketRes.java, src/main/generated/com/appcenter/marketplace/domain/market/dto/res/QMyFavoriteMarketRes.java, src/main/java/com/appcenter/marketplace/domain/market/controller/MarketController.java, src/main/java/com/appcenter/marketplace/domain/market/dto/res/FavoriteMarketRes.java, src/main/java/com/appcenter/marketplace/domain/market/dto/res/MarketRes.java, src/main/java/com/appcenter/marketplace/domain/market/dto/res/MyFavoriteMarketRes.java, src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustom.java, src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustomImpl.java, src/main/java/com/appcenter/marketplace/domain/market/service/MarketService.java, src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketServiceImpl.java
<br>
close #73 
<br>
<br>
<br>
-
<br>
<br>
- [] PR 제목 규칙 잘 지켰는가?
=> [Issue/#73] 매장 리스트 조회 시 신규 쿠폰 여부 추가

src/main/generated/com/appcenter/marketplace/domain/market/dto/res/QLatestCouponRes.java, src/main/generated/com/appcenter/marketplace/domain/market/dto/res/QTopLatestCouponRes.java, src/main/java/com/appcenter/marketplace/domain/market/controller/MarketController.java, src/main/java/com/appcenter/marketplace/domain/market/dto/res/LatestCouponRes.java, src/main/java/com/appcenter/marketplace/domain/market/dto/res/TopLatestCouponRes.java, src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustom.java, src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustomImpl.java, src/main/java/com/appcenter/marketplace/domain/market/service/MarketService.java, src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketServiceImpl.java
<br>
close #72 
<br>
<br>
<br>
-
<br>
<br>
=> [Issue/#72] 최신 등록 쿠폰 리스트 찜 여부 추가 + memberId 별 찜 여부 추가

src/main/generated/com/appcenter/marketplace/domain/market/dto/res/QTopFavoriteMarketRes.java, src/main/java/com/appcenter/marketplace/domain/market/controller/MarketController.java, src/main/java/com/appcenter/marketplace/domain/market/dto/res/TopFavoriteMarketRes.java, src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustom.java, src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustomImpl.java, src/main/java/com/appcenter/marketplace/domain/market/service/MarketService.java, src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketServiceImpl.java
<br>
close #79 
<br>
<br>
<br>
-
<br>
<br>
=> [Issue/#79] Top 인기 매장 리스트 찜 여부 누락 구현

src/main/generated/com/appcenter/marketplace/domain/market/dto/res/QLatestCouponRes.java, src/main/java/com/appcenter/marketplace/domain/market/controller/MarketController.java, src/main/java/com/appcenter/marketplace/domain/market/dto/res/LatestCouponRes.java, src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustom.java, src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustomImpl.java, src/main/java/com/appcenter/marketplace/domain/market/service/MarketService.java, src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketServiceImpl.java
<br>
close #78 
<br>
<br>
-> CASE 문으로 직접 실행
<br>
-
<br>
<br>
=> [Feat/#78] 최신 쿠폰 리스트 "신규 쿠폰" 태그 추가

src/main/generated/com/appcenter/marketplace/domain/cheer/QCheer.java, src/main/generated/com/appcenter/marketplace/domain/member/QMember.java, src/main/generated/com/appcenter/marketplace/domain/requestMarket/QRequestMarket.java, src/main/generated/com/appcenter/marketplace/domain/tempMarket/QTempMarket.java, src/main/java/com/appcenter/marketplace/domain/cheer/Cheer.java, src/main/java/com/appcenter/marketplace/domain/member/Member.java, src/main/java/com/appcenter/marketplace/domain/requestMarket/RequestMarket.java, src/main/java/com/appcenter/marketplace/domain/tempMarket/TempMarket.java
<br>
close #82 
<br>
<br>
<br>
-
<br>
<br>
=> [Feat/#82] 요청, 임시, 응원 테이블 추가 생성 및 회원 응원권 컬럼 추가

src/main/generated/com/appcenter/marketplace/domain/cheer/QCheer.java, src/main/generated/com/appcenter/marketplace/domain/tempMarket/QTempMarket.java, src/main/generated/com/appcenter/marketplace/domain/tempMarket/dto/res/QTempMarketRes.java, src/main/java/com/appcenter/marketplace/domain/cheer/Cheer.java, src/main/java/com/appcenter/marketplace/domain/cheer/CheerRepository.java, src/main/java/com/appcenter/marketplace/domain/cheer/controller/CheerController.java, src/main/java/com/appcenter/marketplace/domain/cheer/service/CheerService.java, src/main/java/com/appcenter/marketplace/domain/cheer/service/impl/CheerServiceImpl.java, src/main/java/com/appcenter/marketplace/domain/tempMarket/TempMarket.java, src/main/java/com/appcenter/marketplace/domain/tempMarket/controller/TempMarketAdminController.java, src/main/java/com/appcenter/marketplace/domain/tempMarket/controller/TempMarketController.java, src/main/java/com/appcenter/marketplace/domain/tempMarket/dto/req/TempMarketReq.java, src/main/java/com/appcenter/marketplace/domain/tempMarket/dto/res/TempMarketDetailRes.java, src/main/java/com/appcenter/marketplace/domain/tempMarket/dto/res/TempMarketHiddenRes.java, src/main/java/com/appcenter/marketplace/domain/tempMarket/dto/res/TempMarketPageRes.java, src/main/java/com/appcenter/marketplace/domain/tempMarket/dto/res/TempMarketRes.java, src/main/java/com/appcenter/marketplace/domain/tempMarket/repository/TempMarketRepository.java, src/main/java/com/appcenter/marketplace/domain/tempMarket/repository/TempMarketRepositoryCustom.java, src/main/java/com/appcenter/marketplace/domain/tempMarket/repository/TempMarketRepositoryImpl.java, src/main/java/com/appcenter/marketplace/domain/tempMarket/service/TempMarketAdminService.java, src/main/java/com/appcenter/marketplace/domain/tempMarket/service/TempMarketService.java, src/main/java/com/appcenter/marketplace/domain/tempMarket/service/impl/TempMarketAdminServiceImpl.java, src/main/java/com/appcenter/marketplace/domain/tempMarket/service/impl/TempMarketServiceImpl.java, src/main/java/com/appcenter/marketplace/global/common/StatusCode.java
<br>
close #87 
<br>
<br>
<br>
-
<br>
<br>
=> [Feat/#87] 임시매장 CRUD API 구현 & 공감하기 API 구현

src/main/java/com/appcenter/marketplace/MarketplaceApplication.java, src/main/java/com/appcenter/marketplace/domain/member/service/impl/MemberServiceImpl.java, src/main/java/com/appcenter/marketplace/domain/requestMarket/repository/RequestMarketRepository.java, src/main/java/com/appcenter/marketplace/domain/tempMarket/controller/TempMarketAdminController.java, src/main/java/com/appcenter/marketplace/domain/tempMarket/repository/TempMarketRepositoryImpl.java, src/main/java/com/appcenter/marketplace/domain/tempMarket/service/TempMarketAdminService.java, src/main/java/com/appcenter/marketplace/domain/tempMarket/service/impl/TempMarketAdminServiceImpl.java, src/main/java/com/appcenter/marketplace/domain/tempMarket/service/impl/TempMarketServiceImpl.java, src/main/java/com/appcenter/marketplace/global/common/StatusCode.java
<br>
close #92 
<br>
- 임시매장 등록시 요청 매장은 삭제되도록 한다.
- 임시매장 전체 조회시 페이징 처리가 되어야 한다. ( 관리자모드 이므로 "웹" 페이징으로 해야한다.)
- 임시매장을 숨김처리 할 시, 조회시 필터를 적용해야 한다.
<br>
<br>
<br>
- 이 부분 `@EnableSpringDataWebSupport(pageSerializationMode = VIA_DTO)` 경고이긴 한데 
일단 주석으로만 해뒀어요. 이거에 따라 응답 형식이 약간 바뀌는데 어떻게 할까요?? 
(Spring3.3 부터 도임된거라고..)
<br>
=> [Refactor/#92] 임시매장 등록 시 요청 매장 삭제 로직 추가 & 페이징 처리 & 숨김처리 필터링 적용

src/main/java/com/appcenter/marketplace/MarketplaceApplication.java, src/main/java/com/appcenter/marketplace/domain/member_coupon/controller/MemberCouponController.java
<br>
close #93 
<br>
<br>
<br>
-
<br>
<br>
=> [Refactor/#93] 회원의 쿠폰 리스트 조회시 url 통일

src/main/java/com/appcenter/marketplace/domain/tempMarket/controller/TempMarketController.java, src/main/java/com/appcenter/marketplace/domain/tempMarket/dto/res/TempMarketRes.java, src/main/java/com/appcenter/marketplace/domain/tempMarket/service/TempMarketService.java, src/main/java/com/appcenter/marketplace/domain/tempMarket/service/impl/TempMarketServiceImpl.java
<br>
close #97 
<br>
<br>
<br>
- TempMarketRes 필드 컬럼 및 생성자 추가
<br>
<br>
=> [Feat] 임시 매장 페이징 검색 api 구현

src/main/generated/com/appcenter/marketplace/domain/coupon/dto/res/QPopularCouponRes.java, src/main/java/com/appcenter/marketplace/domain/coupon/controller/CouponController.java, src/main/java/com/appcenter/marketplace/domain/coupon/dto/res/PopularCouponRes.java, src/main/java/com/appcenter/marketplace/domain/coupon/repository/CouponRepositoryCustom.java, src/main/java/com/appcenter/marketplace/domain/coupon/repository/CouponRepositoryCustomImpl.java, src/main/java/com/appcenter/marketplace/domain/coupon/service/CouponService.java, src/main/java/com/appcenter/marketplace/domain/coupon/service/impl/CouponServiceImpl.java
<br>
close #100 
<br>
- 쿠폰 컨트롤러 메서드명 변경
- 쿠폰 서비스 최신 쿠폰 조회 메서드의 컬럼 명 변경
<br>
<br>
=> [Feat/#100] 발급 쿠폰(member_coupon)의 count 내림차순  인기 쿠폰(coupon) 조회 페이징 구현

build.gradle, src/main/generated/com/appcenter/marketplace/domain/member/QMember.java, src/main/java/com/appcenter/marketplace/domain/cheer/controller/CheerController.java, src/main/java/com/appcenter/marketplace/domain/coupon/controller/CouponController.java, src/main/java/com/appcenter/marketplace/domain/favorite/controller/FavoriteController.java, src/main/java/com/appcenter/marketplace/domain/market/controller/MarketController.java, src/main/java/com/appcenter/marketplace/domain/member/Member.java, src/main/java/com/appcenter/marketplace/domain/member/Role.java, src/main/java/com/appcenter/marketplace/domain/member/controller/MemberController.java, src/main/java/com/appcenter/marketplace/domain/member/dto/req/MemberLoginReq.java, src/main/java/com/appcenter/marketplace/domain/member/service/MemberService.java, src/main/java/com/appcenter/marketplace/domain/member/service/impl/MemberServiceImpl.java, src/main/java/com/appcenter/marketplace/domain/member_coupon/controller/MemberCouponController.java, src/main/java/com/appcenter/marketplace/domain/tempMarket/controller/TempMarketController.java, src/main/java/com/appcenter/marketplace/global/common/StatusCode.java, src/main/java/com/appcenter/marketplace/global/config/SecurityConfig.java, src/main/java/com/appcenter/marketplace/global/config/SwaggerConfig.java, src/main/java/com/appcenter/marketplace/global/exception/JwtExceptionHandlerFilter.java, src/main/java/com/appcenter/marketplace/global/jwt/CustomUserDetails.java, src/main/java/com/appcenter/marketplace/global/jwt/CustomUserDetailsService.java, src/main/java/com/appcenter/marketplace/global/jwt/JwtAuthenticationFilter.java, src/main/java/com/appcenter/marketplace/global/jwt/JwtTokenProvider.java
- [] 리팩토링
<br>
close #114 
<br>
<br>
<br>
-
<br>
<br>
=> [Feat/#114] 시큐리티 적용 + jwt 토큰 사용

.gitignore, build.gradle, local/docker-compose.yml, src/test/java/com/appcenter/marketplace/beta/BetaRepositoryTest.java, src/test/java/com/appcenter/marketplace/image/ImageServiceTest.java
<br>
close #119 
<br>
<br>
<br>
-
<br>
<br>
=> [Test/#119] 서비스 테스트 코드 작성 및 Ngrinder 도커 환경 구축

src/main/generated/com/appcenter/marketplace/domain/member_coupon/dto/res/QIssuedCouponRes.java, src/main/generated/com/appcenter/marketplace/domain/tempMarket/dto/res/QTempMarketRes.java, src/main/java/com/appcenter/marketplace/domain/member/dto/req/MemberLoginReq.java, src/main/java/com/appcenter/marketplace/domain/member/dto/res/MemberLoginRes.java, src/main/java/com/appcenter/marketplace/domain/member/repository/MemberRepositoryImpl.java, src/main/java/com/appcenter/marketplace/domain/member_coupon/dto/res/IssuedCouponRes.java, src/main/java/com/appcenter/marketplace/domain/member_coupon/repository/MemberCouponRepositoryCustomImpl.java, src/main/java/com/appcenter/marketplace/domain/tempMarket/dto/res/TempMarketRes.java, src/main/java/com/appcenter/marketplace/domain/tempMarket/repository/TempMarketRepositoryImpl.java
<br>
close #125 
<br>
<br>
<br>
-
<br>
<br>
=> [Feat/#125] 발급쿠폰 url 가져오기 & 공감권 갯수 제한 늘리기(임시) & 잔여 공감권 조회하기 & 임시 매장 마감 날짜 제공

src/main/generated/queryDsl/com/appcenter/marketplace/domain/beta/QBetaMarket.java, src/main/generated/queryDsl/com/appcenter/marketplace/domain/beta/dto/res/QBetaCouponRes.java, src/main/java/com/appcenter/marketplace/domain/beta/BetaMarket.java, src/main/java/com/appcenter/marketplace/domain/beta/dto/req/BetaMarketReq.java, src/main/java/com/appcenter/marketplace/domain/beta/dto/res/BetaCouponRes.java, src/main/java/com/appcenter/marketplace/domain/beta/dto/res/BetaMarketRes.java, src/main/java/com/appcenter/marketplace/domain/beta/repository/BetaCouponCustomImpl.java, src/main/java/com/appcenter/marketplace/domain/tempMarket/service/impl/TempMarketAdminServiceImpl.java
<br>
close #128 
<br>
<br>
<br>
-
<br>
<br>
=> [feat/#128] 베타버전 매장 제휴 여부 추가

src/main/java/com/appcenter/marketplace/domain/beta/BetaMarket.java, src/main/java/com/appcenter/marketplace/domain/beta/controller/BetaMarketController.java, src/main/java/com/appcenter/marketplace/domain/beta/service/BetaMarketService.java, src/main/java/com/appcenter/marketplace/domain/beta/service/impl/BetaMarketServiceImpl.java
<br>
<br>
<br>
<br>
-
<br>
<br>
=> [feat/#128] 베타버전 매장 정보 수정 추가

src/main/java/com/appcenter/marketplace/domain/coupon/repository/CouponRepository.java, src/main/java/com/appcenter/marketplace/domain/member_coupon/MemberCoupon.java, src/main/java/com/appcenter/marketplace/domain/member_coupon/service/impl/MemberCouponServiceImpl.java, src/test/java/com/appcenter/marketplace/coupon/CouponConcurrentTest.java
<br>
close #131 
<br>
<br>
<br>
- 동일한 사용자가 동시에 쿠폰 발급 시 발급되는 현상 해결
<br>
<br>
=>  [Feat/#131] 쿠폰 발급 동시성 제어(비관적 락) + 중복 발급 방지(DB 유니크 제약조건)

src/main/java/com/appcenter/marketplace/domain/category/Category.java, src/main/java/com/appcenter/marketplace/domain/favorite/Favorite.java, src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustomImpl.java
<br>
close #136 
<br>
**전체 매장 조회**
favorite 데이터 880개 가량 있는 상태
개선 전
개선 후
**응답속도가 75ms -> 45ms로 성능이 향상되었다.**
<br>
**카테고리 별 매장 조회**
favorite 데이터 880개 가량 있는 상태
2000번의 부하테스트 결과
개선 전
개선 후
평균 TPS가 **119.2 -> 162.7**로 무려 36%나 상승했다.
<br>
**자신이 찜한 매장 조회**
favorite 데이터 24000개 가량 있는 상태
2000번의 부하테스트 결과
개선 전
개선 후
평균 TPS가 **61 -> 121**로 **두 배** 차이가 나는 것을 볼 수 있다.
<br>
<br>
-
<br>
<br>
=> [Refactor/#136] 매장 관련 조회 성능 개선

src/main/java/com/appcenter/marketplace/domain/tempMarket/dto/res/TempMarketRes.java
<br>
close #135 
<br>
<br>
<br>
-
<br>
<br>
=> [Issue/#135] 임시 매장 검색 시 오류 해결 

src/main/java/com/appcenter/marketplace/global/config/RedisConfig.java
<br>
close #{이슈넘버}
<br>
<br>
<br>
-
<br>
<br>
=> [Issue] Redis 호스트, 포트 지정 

src/main/generated/queryDsl/com/appcenter/marketplace/domain/member/QMember.java, src/main/java/com/appcenter/marketplace/domain/member/Member.java, src/main/java/com/appcenter/marketplace/domain/member/controller/MemberController.java, src/main/java/com/appcenter/marketplace/domain/member/dto/req/MemberAccountReq.java, src/main/java/com/appcenter/marketplace/domain/member/dto/res/MemberRes.java, src/main/java/com/appcenter/marketplace/domain/member/service/MemberService.java, src/main/java/com/appcenter/marketplace/domain/member/service/impl/MemberServiceImpl.java, src/main/java/com/appcenter/marketplace/global/common/StatusCode.java, src/main/java/com/appcenter/marketplace/global/config/SecurityConfig.java
<br>
close #144 
<br>
<br>
<br>
- MemberLoginRes -> MemberRes로 변경
- 회원 정보 변경 시 캐싱 삭제
<br>
<br>
=> [Feat/144] 회원 주거래은행, 계좌번호 컬럼, CRUD 추가 , 관리자 승급 API 추가, API 권한 설정 구현

src/main/generated/queryDsl/com/appcenter/marketplace/domain/member_payback/dto/res/QReceiptRes.java, src/main/java/com/appcenter/marketplace/domain/image/service/ImageService.java, src/main/java/com/appcenter/marketplace/domain/image/service/impl/ImageServiceImpl.java, src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketOwnerServiceImpl.java, src/main/java/com/appcenter/marketplace/domain/member/service/impl/MemberServiceImpl.java, src/main/java/com/appcenter/marketplace/domain/member_payback/MemberPayback.java, src/main/java/com/appcenter/marketplace/domain/member_payback/controller/MemberPaybackAdminController.java, src/main/java/com/appcenter/marketplace/domain/member_payback/controller/MemberPaybackController.java, src/main/java/com/appcenter/marketplace/domain/member_payback/dto/res/ReceiptRes.java, src/main/java/com/appcenter/marketplace/domain/member_payback/repository/MemberPaybackRepositoryCustom.java, src/main/java/com/appcenter/marketplace/domain/member_payback/repository/MemberPaybackRepositoryCustomImpl.java, src/main/java/com/appcenter/marketplace/domain/member_payback/service/MemberPaybackAdminService.java, src/main/java/com/appcenter/marketplace/domain/member_payback/service/MemberPaybackService.java, src/main/java/com/appcenter/marketplace/domain/member_payback/service/impl/MemberPaybackAdminServiceImpl.java, src/main/java/com/appcenter/marketplace/domain/member_payback/service/impl/MemberPaybackServiceImpl.java, src/main/java/com/appcenter/marketplace/global/common/StatusCode.java, src/main/java/com/appcenter/marketplace/global/config/ImageConfig.java
<br>
close #147 
<br>
<br>
<br>
-
<br>
<br>
=> [Feat/#147] 영수증 제출 및 회원 영수증 조회 API 추가 구현
